version: "3.9"

services:
  postgres:
    container_name: shortlink-postgres
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: shortlink_pass
      POSTGRES_DB: url_shortener
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db-init:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d url_shortener"]
      interval: 5s
      timeout: 5s
      retries: 10

  backend:
    build: ./backend
    container_name: shortlink-backend
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/url_shortener
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: shortlink_pass
      SPRING_JPA_HIBERNATE_DDL_AUTO: update

  frontend:
    build: ./frontend
    container_name: shortlink-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  pgdata:
